### PR TITLE
migrate bug_report link to radian software org

### PR DESCRIPTION
**Pull request by tshu-w**
migrate link in `bug_report.md`

### CODE REVIEW

**Comment by progfolio** [comment]
Thank you for your contribution.
It looks like `.github/PULL_REQUEST_TEMPLATE.md` contains a link to the old repository address, too. Would you like to update that as well?

**Comment by tshu-w** [comment]
> Thank you for your contribution.
> It looks like `.github/PULL_REQUEST_TEMPLATE.md` contains a link to the old repository address, too. Would you like to update that as well?

Done.

**Comment by progfolio** [comment]
Merged to "develop". Thanks again.

**Comment by domq** [comment]
Was wondering about radian vs. raxod502 as well, and stopped short of mounting a full-blown police investigation into which of the GitHub URLs was the legit one. Kindly merge into master soon.

**Comment by raxod502** [comment]
I merged this and previous commits into master since they had been on develop for a while.

**Pull request merged**
